### ISSUE TITLE
Support for ControlValueAccessor

### ISSUE THREAD

**Issue by mattlocker** [timdeschryver/ng-signal-forms#33]
Are there any plans to include support for [ControlValueAccessor](https://angular.io/api/forms/ControlValueAccessor) or introduce a similar concept? From my point of view reusable form components are very important in enterprise apps which may include very complex forms.

**Comment by timdeschryver** [comment]
Hey @mattlocker have you tried using a CVA with Signal Forms?
I was thinking this should just work out of the box because you just bind to a `ngModel`, which will be read/updated by the CVA.

**Comment by mattlocker** [comment]
Oh for sure you are right(silly me), thank you for pointing that out. I'll perform my tests and in the meantime, I close the issue.

**Comment by timdeschryver** [comment]
Cool, let me know how it works.
And if you want, you can always contribute to this library by providing an example in an existing form, or in a new form.
